FROM nvidia/cuda:13.1.0-runtime-ubuntu24.04

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install torch --index-url https://download.pytorch.org/whl/cu130 && \
    pip install instmodel[pytorch] pytest
